### ISSUE TITLE
Possible errors

### ISSUE THREAD

**Issue by ytrewqytrewqytrewqytrewq1** [mgp25/RE-WhatsApp#1]
Hi thank you for your work,
we got in touch on twitter (@m_atbrik) a couple of weeks ago, 
reading your description of the registration process I noticed something off, maybe because of updates (i'm working to whatsapp v2.18.264 for Android):

the request for v.whatsapp.net/v2/code has an extra field id 

```
mistyped=6
&cc=39
&in=3493233081
&id=%c1%bd%d78%c5z1V%ab7%9c%7f%bd%ff%a3%25%a1%e1%c0%c6
&lg=en
&lc=US
&mcc=000
&mnc=000
&sim_mcc=000
&sim_mnc=000
&method=sms
&reason=
&token=qz91WSreKBRZo%2fUjNEvlDLbvPIQ%3d
&authkey=GQQGZQlgbjL%2d9rVZdNwRol8bZEAgLoRmJIetnhZQQCo
&e_regid=F2x0vQ
&e_keytype=BQ
&e_ident=XXPSw3pYBPW4kuxHOWOcgbU2owmJCdHDdj6%2davYphVQ
&e_skey_id=AAAA
&e_skey_val=KsU6W6UsiLk6eZds%5f7TNqjj3n5WuWQOlUUZzaaIYiSQ
&e_skey_sig=UODXHJP72ejPY%5fOi9AIivaGQMvwDKqJ%2dm6IAmKpFXXlp0oe7ZY%2dtTSrD%5fz4YZ6bnSLYU8trT8ZrJG5uSTuTwAA
&network_radio_type=1
&simnum=0
&hasinrc=1
&pid=10914
&rc=0
```

the rc values are a little different 

```java
public enum c implements com.google.protobuf.k.a {
            RELEASE(0),
            BETA(1),
            ALPHA(2),
            DEBUG(3);    
```

**Comment by mgp25** [comment]
Hello @ytrewqytrewqytrewqytrewq1, 

Yes, I forgot to add it. I'll add it in the next commit. Talking about the rc values, I'll recheck it, but it seems you are right. Thanks for repoting it.

Another thing I forgot to add was the info for `reason` param.

`reason`: If jailbroken `jailbroken` else `` 

**Note:** I am reversing both iOS and Android versions simultaneously, so I am not sure if `jailbroken` value applies to Android versions too.

**Comment by mgp25** [comment]
Hello @ytrewqytrewqytrewqytrewq1,

Updated content in latest commits.

Regards
