### ISSUE TITLE
How to get WA Android APK Signature

### ISSUE THREAD

**Issue by shekohex** [mgp25/RE-WhatsApp#3]
In  [Android Token](https://github.com/mgp25/RE-WhatsApp/blob/master/README.md#android-token)

You referring to something is called Signature. I know what it is, but how do i get it ?
I manged to test it with the latest version of whatsapp `2.18.378` after of course getting the new WhatsApp `classes.dex` md5.

BTW, i searched for an answer, but what i found that they all trying to refer to something `*.RSA` in the `META-INF` of the apk.
I then realized that WhatsApp actually uses `DSA` for this, that's not the problem then, they all keys.

So, can you please explain a little bit how can I get that signature ? 

Thanks.

**Comment by mgp25** [comment]
Well, the answer is simple, doing it is more complex are requires time. Reverse engineering, it is hardcoded and obfuscated somewhere in the app 😄 

Regards

**Comment by shekohex** [comment]
@mgp25
Ok, fine
Since you have mentioned `Reverse Engineering`, i already have a semi-full java source code of the apk, it's much more readable than `smali`, yeah it's not perfect but it's much better to work with. It's not a hard task to do that __i think__.
I already found the `Salt` already hardcoded somewhere, so i think i would find the signature as well.

BTW, any hints to get it ?
Thanks again 😀.

**Comment by mgp25** [comment]
I don't think giving more information would be more beneficial. You know Facebook isn't in its greatest moment, and they will take aggresive decisions about any information disclosure. Said that, I think what has been posted is enough for anyone to continue in their own.

Try harder. If you got part of it, you are just half way there. Keep trying!

Regards
