### ISSUE TITLE
How to decrypt the ENC?

### ISSUE THREAD

**Issue by ZRginger** [mgp25/RE-WhatsApp#6]
@mgp25  
Hi, recently I  need to analyse the process of whatsApp's registration. And I already use proxy to catch the packages between server and client. But I just get ENC parameter. Although you have told me that what the enc contains, I want to decrypt the enc and compare the result.

**Comment by mgp25** [comment]
Actually, you can't. It is encrypted using WhatsApp server public key. It means only WhatsApp private key can decrypt that information. WhatsApp Private Key is in WhatsApp server.

So answering to your question. You can't decrypt the encrypted ENC data.

Regards

**Comment by ZRginger** [comment]
> Actually, you can't. It is encrypted using WhatsApp server public key. It means only WhatsApp private key can decrypt that information. WhatsApp Private Key is in WhatsApp server.
> 
> So answering to your question, you can't decrypt the encrypted ENC data.
> 
> Regards
 Well, I still don't understand. Because you said they encrypt the enc data using DH. So theoretically the client also can decrypt the encrypted ENC data.

**Comment by mgp25** [comment]
@ZRginger you are right. I completely forgot about the DH. In order to decrypt it, just generate the AES key and perform the decryption in AES GCM mode

Regards

**Comment by ZRginger** [comment]
> @ZRginger you are right. I completely forgot about the DH. In order to decrypt it, just generate the AES key (agreement) and perform the decryption in AES GCM mode
> 
> Regards

But I have no idea where the key stored or how to generate the AES key.

**Comment by socialAPIS** [comment]
I have a decrypted version it's nothing special, you can read the docs on my or mgp25s repo for WhatsApp
